#!/bin/bash
# brain-daily-done-summary.sh - Generate 3-line DONE summary for today
# Usage: brain-daily-done-summary.sh [--date YYYY-MM-DD] [--output memory/YYYY-MM-DD.md] [--dry-run]
#
# Reads links.md for DONE entries today and generates:
# 1. Count of completed items
# 2. Top 3 titles
# 3. Key themes/categories

set -eo pipefail

# === Config ===
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORKSPACE_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SECOND_BRAIN_DIR="${SECOND_BRAIN_DIR:-${WORKSPACE_ROOT}/memory/second-brain}"
LINKS_FILE="${SECOND_BRAIN_DIR}/links.md"
MEMORY_DIR="${MEMORY_DIR:-${WORKSPACE_ROOT}/memory}"

# === Args ===
TARGET_DATE=""
OUTPUT_FILE=""
DRY_RUN=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --date) TARGET_DATE="$2"; shift 2 ;;
        --output) OUTPUT_FILE="$2"; shift 2 ;;
        --dry-run) DRY_RUN=true; shift ;;
        *) echo "Unknown arg: $1" >&2; exit 1 ;;
    esac
done

# === Default date = today ===
if [[ -z "$TARGET_DATE" ]]; then
    TARGET_DATE=$(date "+%Y-%m-%d")
fi

if [[ -z "$OUTPUT_FILE" ]]; then
    OUTPUT_FILE="${MEMORY_DIR}/${TARGET_DATE}.md"
fi

# === Validate ===
if [[ ! -f "$LINKS_FILE" ]]; then
    echo "No links file found at $LINKS_FILE"
    exit 0
fi

# === Extract DONE entries for target date ===
# Pattern: ## [YYYY-MM-DD HH:MM:SS] title ... - Status: DONE ... - Added: YYYY-MM-DD
DONE_TITLES=()
DONE_URLS=()

# Use awk to extract DONE entries added on target date
while IFS= read -r line; do
    if [[ -n "$line" ]]; then
        DONE_TITLES+=("$line")
    fi
done < <(awk -v date="$TARGET_DATE" '
    /^## \[/ {
        # Extract timestamp from header
        match($0, /\[([0-9-]+) /, ts)
        header_date = ts[1]
        title = $0
        sub(/^## \[[^]]+\] /, "", title)
        in_entry = 1
        current_title = title
        current_date = ""
        current_status = ""
    }
    in_entry && /^- Added:/ {
        current_date = $3
    }
    in_entry && /^- Status:/ {
        current_status = $3
    }
    in_entry && /^$/ {
        # End of entry
        if (current_status == "DONE" && current_date == date) {
            print current_title
        }
        in_entry = 0
    }
    END {
        if (in_entry && current_status == "DONE" && current_date == date) {
            print current_title
        }
    }
' "$LINKS_FILE" 2>/dev/null)

DONE_COUNT=${#DONE_TITLES[@]}

# === Generate summary ===
if [[ $DONE_COUNT -eq 0 ]]; then
    SUMMARY="# 📋 Daily DONE Summary: $TARGET_DATE

No completed items for this date.

---
_Generated by brain-daily-done-summary.sh_"
else
    # Build top 3 titles
    TOP_TITLES=""
    for i in "${DONE_TITLES[@]:0:3}"; do
        TOP_TITLES="${TOP_TITLES}- $i
"
    done
    [[ -z "$TOP_TITLES" ]] && TOP_TITLES="- (none)"

    SUMMARY="# 📋 Daily DONE Summary: $TARGET_DATE

**✅ Completed:** $DONE_COUNT item(s)

### Top Items:
$TOP_TITLES
---
_Generated by brain-daily-done-summary.sh_"
fi

# === Output ===
if $DRY_RUN; then
    echo "[DRY-RUN] Would output:"
    echo "$SUMMARY"
    exit 0
fi

# Write to stdout
echo "$SUMMARY"

# Append to daily memory file if exists or creates new
if [[ -d "$(dirname "$OUTPUT_FILE")" ]]; then
    echo "" >> "$OUTPUT_FILE"
    echo "$SUMMARY" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "OK: Summary appended to $OUTPUT_FILE"
fi
