#!/bin/bash
# brain-todoist-done-summary.sh - Generate 3-line DONE summary for today
# Usage: brain-todoist-done-summary.sh [--dry-run] [--date YYYY-MM-DD] [--output json|text|markdown]
#
# Purpose: Create concise summary of completed tasks for Discord/Telegram
# Output: Top 3 completed items with total count
#
# Exit codes:
#   0 - Success (may have no completed tasks)
#   1 - API error
#   2 - Auth error (missing/invalid token)
#   3 - jq not available
#
# Limitations:
#   - Todoist /tasks/completed endpoint returns last 100 completed tasks
#   - Cannot filter by project via API; filters client-side
#   - Timezone handling assumes server is in KST (Asia/Seoul)

set -eo pipefail

# === Config ===
CREDENTIALS_DIR="/root/.openclaw/credentials"
TODOIST_TOKEN=""
PROJECTS_FILE="${CREDENTIALS_DIR}/todoist-projects.json"
API_BASE="https://api.todoist.com/api/v1"

# Default values
DRY_RUN=false
TARGET_DATE=""
OUTPUT_FORMAT="text"

# === Parse args ===
while [[ $# -gt 0 ]]; do
    case $1 in
        --dry-run) DRY_RUN=true; shift ;;
        --date) TARGET_DATE="$2"; shift 2 ;;
        --output) OUTPUT_FORMAT="$2"; shift 2 ;;
        --help|-h)
            cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Generate a 3-line summary of completed tasks for today.

Options:
  --dry-run      Show sample output without API calls
  --date DATE    Target date (YYYY-MM-DD, default: today)
  --output FMT   Output format: text|json|markdown (default: text)
  --help         Show this help

Examples:
  $(basename "$0")                    # Today's completed tasks
  $(basename "$0") --date 2026-02-28  # Specific date
  $(basename "$0") --dry-run          # Preview sample output

Output (text format):
  Line 1: Count summary
  Line 2-4: Top 3 completed items
  
Exit codes: 0=OK, 1=API error, 2=Auth error, 3=Missing jq
EOF
            exit 0
            ;;
        *) echo "Unknown arg: $1" >&2; exit 1 ;;
    esac
done

# === Dependencies ===
if ! command -v jq &>/dev/null; then
    echo "ERROR: jq is required but not installed" >&2
    exit 3
fi

# === Default date = today ===
if [[ -z "$TARGET_DATE" ]]; then
    TARGET_DATE=$(date "+%Y-%m-%d")
fi

# === Load token ===
if [[ -f "${CREDENTIALS_DIR}/todoist" ]]; then
    TODOIST_TOKEN=$(cat "${CREDENTIALS_DIR}/todoist")
else
    echo "ERROR: Todoist token not found at ${CREDENTIALS_DIR}/todoist" >&2
    exit 2
fi

if [[ -z "$TODOIST_TOKEN" ]]; then
    echo "ERROR: Todoist token is empty" >&2
    exit 2
fi

# === Dry-run mode ===
if $DRY_RUN; then
    cat <<EOF
[DRY-RUN] Sample output for $TARGET_DATE

✅ Completed Today: 3 tasks

1. [Active] OpenClaw iOS 앱 Xcode 빌드 & 애플워치 연동 테스트
2. [Waiting] 카카오 로그인 KOE004 처리 완료
3. [Active] gog 빌드 - 릴리스 바이너리로 재시도

---
Generated by brain-todoist-done-summary.sh
EOF
    exit 0
fi

# === Load project names for display ===
PROJECT_NAMES="{}"
if [[ -f "$PROJECTS_FILE" ]]; then
    PROJECT_NAMES=$(jq -c '
        {
            (.active): "Active",
            (.waiting): "Waiting",
            (.queue): "Queue",
            (.inbox): "Inbox"
        }
    ' "$PROJECTS_FILE" 2>/dev/null || echo "{}")
fi

# === Fetch completed tasks ===
result=$(curl -s -w "\n%{http_code}" -X GET "${API_BASE}/tasks/completed?limit=100" \
    -H "Authorization: Bearer ${TODOIST_TOKEN}" \
    -H "Content-Type: application/json" 2>/dev/null)

http_code=$(echo "$result" | tail -1)
body=$(echo "$result" | sed '$d')

if [[ "$http_code" != "200" ]]; then
    echo "ERROR: API returned HTTP $http_code" >&2
    echo "$body" >&2
    exit 1
fi

# === Filter by date ===
# Todoist returns completed_at in UTC. Convert TARGET_DATE to UTC range.
# KST = UTC+9, so KST day 00:00-23:59 = UTC previous day 15:00 to same day 14:59
TARGET_DATE_START="${TARGET_DATE}T00:00:00"
TARGET_DATE_END="${TARGET_DATE}T23:59:59"

# Convert KST times to UTC (KST = UTC+9, so subtract 9 hours)
# Using TZ=Asia/Seoul to interpret input as KST, then output as UTC
START_UTC=$(TZ=Asia/Seoul date -d "${TARGET_DATE_START}" -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null)
END_UTC=$(TZ=Asia/Seoul date -d "${TARGET_DATE_END}" -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null)

# Fallback for macOS (less common in prod)
if [[ -z "$START_UTC" ]]; then
    START_UTC=$(date -v-9H -j -f "%Y-%m-%dT%H:%M:%S" "${TARGET_DATE_START}" +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null)
    END_UTC=$(date -v-9H -j -f "%Y-%m-%dT%H:%M:%S" "${TARGET_DATE_END}" +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null)
fi

# Filter tasks completed on target date
COMPLETED_TODAY=$(echo "$body" | jq --arg start "$START_UTC" --arg end "$END_UTC" --argjson names "$PROJECT_NAMES" '
    .items | 
    map(select(.completed_at >= $start and .completed_at <= $end)) |
    map(. + {project_name: ($names[.project_id] // "Other")}) |
    sort_by(.completed_at) | reverse
')

DONE_COUNT=$(echo "$COMPLETED_TODAY" | jq 'length')
TOP_3=$(echo "$COMPLETED_TODAY" | jq '.[0:3]')

# === Output ===
case "$OUTPUT_FORMAT" in
    json)
        echo "$COMPLETED_TODAY" | jq '{
            date: "'"$TARGET_DATE"'",
            total_completed: length,
            top_3: .[0:3]
        }'
        ;;
    markdown)
        echo "## ✅ Completed Today: $DONE_COUNT task(s)"
        echo ""
        if [[ "$DONE_COUNT" -gt 0 ]]; then
            echo "$TOP_3" | jq -r '.[] | "- [\(.project_name)] \(.content)"'
        else
            echo "_No tasks completed today._"
        fi
        echo ""
        echo "---"
        echo "_Generated by brain-todoist-done-summary.sh_"
        ;;
    text|*)
        echo "✅ Completed Today ($TARGET_DATE): $DONE_COUNT task(s)"
        echo ""
        if [[ "$DONE_COUNT" -eq 0 ]]; then
            echo "No tasks completed yet."
        else
            i=1
            echo "$TOP_3" | jq -c '.[]' | while read -r task; do
                content=$(echo "$task" | jq -r '.content')
                project=$(echo "$task" | jq -r '.project_name')
                echo "${i}. [$project] $content"
                ((i++))
            done
            
            if [[ "$DONE_COUNT" -gt 3 ]]; then
                echo ""
                echo "... and $((DONE_COUNT - 3)) more"
            fi
        fi
        ;;
esac

exit 0
